# {"Bright pink (Crayola)":"","Sunglow":"ffd166","Emerald":"06d6a0","Blue (NCS)":"118ab2","Midnight green":"073b4c"}

global_settings:
  font: "Poppins"
  size_title: 36
  size_supstitle: 18
  size: "200px"
  font_color: "white"

wekelijks-raak:
  color: "#ef476f"
  suptitle: "wekelijks"
  title: "raak"
